# Generated by Django 2.2.1 on 2019-05-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190514_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
